/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

//** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
//};

module.exports = {
  Sidebar10: [
    // IT-Kern-Diensteitungen - sind nicht auswählbar
    'Ueber',
    {
      type: 'autogenerated',
      dirName: '10-About',
    }, ],
    Sidebar20: [
      // IT-Business-Diensteitungen - können vom Kunden bestellt werden.
      'Leitungen',
      {
        type: 'autogenerated',
        dirName: '20-Leistungen',
      }, ],
  Sidebar40: [
    // IT-Arbeitsplätze
    'Unser-Auge',
    {
      type: 'autogenerated',
      dirName: '40-Unser-Auge',
    }, ],
    
  Sidebar80: [
    'Kontakt',
    {
      type: 'autogenerated',
      dirName: '80-Kontakt',
    }, ],
  };
